### ISSUE TITLE
[REQ] \e\ build

### ISSUE THREAD

**Issue by MarcoRavich** [KonstaT/android_device_huawei_y560#1]
Hi there,
even if we know that this device is obsolete, it would be great to give it the last chance by building [\e\ (aka deGoogled-Lineage)](https://e.foundation/) for it.

We've opened a 3ad @ [\e\ community](https://community.e.foundation/) linking your repos too:

https://community.e.foundation/t/huawei-y5-y560-l01-l02-l03-l23-u23/24442

Hope can "inspire" you.

Thanks in advance.

**Comment by KonstaT** [comment]
Sorry, not going to happen. I've retired this device from development years ago.

**Comment by MarcoRavich** [comment]
Thanks anyway, however hope you'll consider to build \e\ for devices you're maintaining nowdays.
